### ISSUE TITLE
Configured Container , Restart,  Service Running OK,  Lost  Configuration  

### ISSUE THREAD

**Issue by TaylorGotIT** [vyos/vyos#1]
# history cmd lines 
~$ show  history | grep container
  492  2024-01-17T11:56:26+0800 add container image adguard/adguardhome
  496  2024-01-17T11:58:17+0800 set container name AdGuardHome image 'docker.io/adguard/adguardhome:latest'
  497  2024-01-17T11:58:18+0800 set container name AdGuardHome allow-host-networks
  498  2024-01-17T11:58:18+0800 set container name AdGuardHome volume dir destination '/opt/adguardhome/conf'
  499  2024-01-17T11:58:19+0800 set container name AdGuardHome volume dir source '/opt/adguardhome'
  548  2024-01-17T11:59:05+0800 run show container log AdGuardHome
  565  2024-01-17T12:04:50+0800 restart container AdGuardHome
  576  2024-01-17T12:15:53+0800 restart container AdGuardHome
  583  2024-01-17T12:18:57+0800  show container log AdGuardHome
  987  2024-01-30T10:22:32+0800 show conf co | grep container
  988  2024-01-30T10:23:02+0800 show container log
 1007  2024-01-30T16:44:39+0800 show conf co | grep container
 1016  2024-01-30T16:47:48+0800 show  history | grep container

# podman is running this image 
~$ ps -aux | grep podman
root      4431  0.0  0.0  80184  2012 ?        Ssl  Jan29   0:00 /usr/bin/conmon --api-version 1 -c 2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788 -u 2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788 -r /usr/bin/runc -b /usr/lib/live/mount/persistence/container/storage/overlay-containers/2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788/userdata -p /run/containers/storage/overlay-containers/2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788/userdata/pidfile -n AdGuardHome --exit-dir /run/libpod/exits --socket-dir-path /run/libpod/socket -s -l k8s-file:/usr/lib/live/mount/persistence/container/storage/overlay-containers/2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788/userdata/ctr.log --log-level warning --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/run/containers/storage/overlay-containers/2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788/userdata/oci-log -t --conmon-pidfile /run/vyos-container-AdGuardHome.service.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /usr/lib/live/mount/persistence/container/storage --exit-command-arg --runroot --exit-command-arg /run/containers/storage --exit-command-arg --log-level --exit-command-arg warning --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/libpod --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay2 --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 2c1fbd8bface30fbabff98d9e834136a7b56f8da391eae3273c3009c90618788
bothwin  28492  0.0  0.0   6204   896 pts/0    S+   16:49   0:00 grep podman

# log is ok
~$ sudo podman logs --latest
2024/01/29 09:59:27.026767 [info] AdGuard Home, version v0.107.43
2024/01/29 09:59:27.030788 [info] tls: using default ciphers
2024/01/29 09:59:27.041963 [info] safesearch default: reset 253 rules
2024/01/29 09:59:27.050519 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2024/01/29 09:59:27.054583 [info] auth: initialized.  users:1  sessions:0
2024/01/29 09:59:27.054674 [info] AdGuard Home updates are disabled
2024/01/29 09:59:27.054743 [info] web: initializing
2024/01/29 09:59:27.064040 [info] dnsproxy: cache: enabled, size 4096 b
2024/01/29 09:59:27.064174 [info] dnsproxy: max goroutines is set to 300
2024/01/29 09:59:27.066278 [info] AdGuard Home is available at the following addresses:
2024/01/29 09:59:27.069627 [info] clients: processing addresses
2024/01/29 09:59:27.080115 [info] go to http://127.0.0.1:80
2024/01/29 09:59:27.080176 [info] go to http://192.168.8.1:80
2024/01/29 09:59:27.093854 [info] dnsproxy: starting dns proxy server
2024/01/29 09:59:27.094051 [info] The server is configured to refuse ANY requests
2024/01/29 09:59:27.094125 [info] dnsproxy: cache: enabled, size 4194304 b
2024/01/29 09:59:27.094201 [info] dnsproxy: max goroutines is set to 300
2024/01/29 09:59:27.094435 [info] dnsproxy: creating udp server socket 127.0.0.1:53
2024/01/29 09:59:27.094654 [info] dnsproxy: listening to udp://127.0.0.1:53
2024/01/29 09:59:27.094734 [info] dnsproxy: creating tcp server socket 127.0.0.1:53
2024/01/29 09:59:27.094872 [info] dnsproxy: listening to tcp://127.0.0.1:53
2024/01/29 09:59:27.096700 [info] dnsproxy: entering udp listener loop on 127.0.0.1:53
2024/01/29 09:59:27.096918 [info] dnsproxy: entering tcp listener loop on 127.0.0.1:53
2024/01/29 09:59:33.000699 [info] filtering: saving contents of filter 1 into "/opt/adguardhome/work/data/filters/1.txt"
2024/01/29 09:59:33.030474 [info] filtering: updated filter 1: 1252805 bytes, 63547 rules
2024/01/29 09:59:33.030502 [info] filtering: updated filter 1; rule count: 63547 (was 0)

# But the container part is not in current config cmd
$ show conf co | grep container
$ show conf co | grep  AdGuardHome

# config.boot file is OKay.
:~$ cat /config/config.boot
container {
    name AdGuardHome {
        allow-host-networks
        image docker.io/adguard/adguardhome:latest
        volume dir {
            destination /opt/adguardhome/conf
            source /opt/adguardhome
        }
    }
}

**Comment by andamasov** [comment]
We not provide support here
